export type AppRole = 'founder' | 'mentor' | 'staff';

export type StartupStage = 'ideation' | 'pre_seed' | 'seed' | 'scale';

export type FaqItem = {
  id: string;
  q_pt: string;
  a_pt: string;
  q_en: string;
  a_en: string;
  tags: string[];
  roles: AppRole[];
  stages: StartupStage[];
};

export const FAQ_ITEMS: FaqItem[] = [
  // ─── GENERAL / ONBOARDING ────────────────────────────────────────
  {
    id: 'faq-01',
    q_pt: 'Para que serve esta plataforma?',
    a_pt: 'É o "sistema operativo" do ecossistema da Startup Leiria: acompanha progresso, sessões de mentoria, ações, KPIs, documentos, datarooms e programas — com foco em reduzir fricção e aumentar a qualidade do acompanhamento.',
    q_en: 'What is this platform for?',
    a_en: 'It is the Startup Leiria ecosystem "operating system": it tracks progress, mentoring sessions, actions, KPIs, documents, datarooms, and programs — focused on reducing friction and improving support quality.',
    tags: ['onboarding', 'value'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-02',
    q_pt: 'Quem vê o quê? (perfis e permissões)',
    a_pt: 'Founders veem apenas a(s) sua(s) startup(s). Mentores veem as startups onde estão ligados e as sessões associadas. Consultores veem o portefólio que gerem (e, se autorizado, visão do ecossistema). Administrativos têm acesso a operações, programas, utilizadores e configurações.',
    q_en: 'Who can see what? (profiles and permissions)',
    a_en: 'Founders see only their own startup(s). Mentors see startups they are assigned to and related sessions. Consultants see their managed portfolio (and, if authorized, ecosystem view). Admins have access to operations, programs, users, and settings.',
    tags: ['permissions', 'security'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-02b',
    q_pt: 'Posso mudar o idioma da plataforma?',
    a_pt: 'Sim. A plataforma suporta Português e Inglês. Muda o idioma no menu do perfil ou nas definições. Toda a interface adapta-se automaticamente.',
    q_en: 'Can I change the platform language?',
    a_en: 'Yes. The platform supports Portuguese and English. Switch the language in the profile menu or settings. The entire interface adapts automatically.',
    tags: ['i18n', 'settings'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-02c',
    q_pt: 'Como altero o meu perfil e password?',
    a_pt: 'Vai a "Definições" na barra lateral. Podes atualizar o teu nome, avatar, email de contacto e password. As alterações são guardadas imediatamente.',
    q_en: 'How do I change my profile and password?',
    a_en: 'Go to "Settings" in the sidebar. You can update your name, avatar, contact email, and password. Changes are saved immediately.',
    tags: ['settings', 'security'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── FOUNDER: REGISTRATION & ONBOARDING ──────────────────────────
  {
    id: 'faq-f01',
    q_pt: 'Como me registo como Founder?',
    a_pt: 'Cria uma conta na página de registo com email e password. A tua conta fica "Pendente" até um administrador a aprovar. Recebes um email quando fores aprovado.',
    q_en: 'How do I register as a Founder?',
    a_en: 'Create an account on the registration page with email and password. Your account stays "Pending" until an administrator approves it. You will receive an email when approved.',
    tags: ['onboarding', 'registration'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-f02',
    q_pt: 'O que acontece depois da aprovação da minha conta?',
    a_pt: 'Após aprovação, fazes login e és guiado pelo Onboarding Wizard em 5 passos: assinatura de NDA, informação da empresa, representante legal, seleção de programa e convite da equipa.',
    q_en: 'What happens after my account is approved?',
    a_en: 'After approval, you log in and are guided through the Onboarding Wizard in 5 steps: NDA signing, company information, legal representative, program selection, and team invitation.',
    tags: ['onboarding', 'registration'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-f03',
    q_pt: 'O que é o workspace e como é criado?',
    a_pt: 'O workspace é o espaço digital da tua startup. Pode ser criado automaticamente durante o onboarding ou atribuído por um administrador. Contém milestones, ações, KPIs, documentos e sessões.',
    q_en: 'What is a workspace and how is it created?',
    a_en: 'The workspace is your startup\'s digital space. It can be created automatically during onboarding or assigned by an administrator. It contains milestones, actions, KPIs, documents, and sessions.',
    tags: ['onboarding', 'navigation'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-f04',
    q_pt: 'Como convido membros da minha equipa?',
    a_pt: 'Durante o onboarding (passo 5) ou depois em "A Minha Startup > Equipa". Cada membro recebe um convite por email e pode aceder ao workspace partilhado.',
    q_en: 'How do I invite my team members?',
    a_en: 'During onboarding (step 5) or later in "My Startup > Team". Each member receives an email invitation and can access the shared workspace.',
    tags: ['onboarding', 'teams'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── FOUNDER: MILESTONES & ACTIONS ────────────────────────────────
  {
    id: 'faq-f05',
    q_pt: 'O que são Milestones e como os defino?',
    a_pt: 'Milestones são marcos estratégicos da tua jornada (ex: "Validar problema", "Primeiro cliente pagante"). São pré-carregados com base na tua fase e programa, mas podes personalizá-los.',
    q_en: 'What are Milestones and how do I set them?',
    a_en: 'Milestones are strategic markers in your journey (e.g., "Validate problem", "First paying customer"). They are pre-loaded based on your stage and program, but you can customize them.',
    tags: ['milestones', 'planning'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-f06',
    q_pt: 'Como crio e priorizo ações?',
    a_pt: 'Em "Ações & Plano" ou diretamente num milestone. Define título, prazo e prioridade (Alta/Média/Baixa). As ações prioritárias aparecem no teu dashboard "Focus Today".',
    q_en: 'How do I create and prioritize actions?',
    a_en: 'In "Actions & Plan" or directly within a milestone. Set a title, due date, and priority (High/Medium/Low). Priority actions appear on your "Focus Today" dashboard.',
    tags: ['actions', 'planning'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── FOUNDER: KPIs ────────────────────────────────────────────────
  {
    id: 'faq-05',
    q_pt: 'O que são Objetivos & KPIs e como devo usar?',
    a_pt: 'Objetivos definem "para onde vamos"; KPIs medem "se estamos a lá chegar". Mantém poucos KPIs por objetivo, atualiza regularmente e usa-os como base para decisões e prioridades nas sessões.',
    q_en: 'What are Objectives & KPIs and how should I use them?',
    a_en: 'Objectives define "where we are going"; KPIs measure "if we are getting there". Keep few KPIs per objective, update regularly, and use them as a basis for decisions and priorities in sessions.',
    tags: ['kpis', 'metrics', 'planning'],
    roles: ['founder', 'staff', 'mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-f07',
    q_pt: 'Com que frequência devo atualizar os KPIs?',
    a_pt: 'Idealmente semanalmente, no check-in. A plataforma mostra setas de tendência (↑ ↓ →) para que tu e o consultor vejam evolução. KPIs sem atualização há mais de 2 semanas são sinalizados.',
    q_en: 'How often should I update KPIs?',
    a_en: 'Ideally weekly, during check-in. The platform shows trend arrows (↑ ↓ →) so you and your consultant can see progress. KPIs without updates for more than 2 weeks are flagged.',
    tags: ['kpis', 'metrics'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-f08',
    q_pt: 'O que é o Weekly Check-in?',
    a_pt: 'É um formulário rápido semanal onde atualizas KPIs, reportas bloqueios e indicas prioridades. Demora ~5 minutos e dá ao teu consultor visibilidade do estado atual sem necessitar de reunião.',
    q_en: 'What is the Weekly Check-in?',
    a_en: 'It is a quick weekly form where you update KPIs, report blockers, and indicate priorities. It takes ~5 minutes and gives your consultant visibility into the current state without needing a meeting.',
    tags: ['kpis', 'checkins'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── FOUNDER: DOCUMENTS & DATAROOM ────────────────────────────────
  {
    id: 'faq-07',
    q_pt: 'Onde estão os documentos e templates? Posso partilhar com investidores?',
    a_pt: 'Em "Documentos" encontras uploads, links e templates num repositório único. Podes organizar por categoria e adicionar itens ao Dataroom para partilha externa controlada (links com validade).',
    q_en: 'Where are documents and templates? Can I share with investors?',
    a_en: 'In "Documents" you will find uploads, links, and templates in a single repository. You can organize by category and add items to the Dataroom for controlled external sharing (time-limited links).',
    tags: ['documents', 'templates', 'dataroom'],
    roles: ['founder', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-09',
    q_pt: 'O que é o Dataroom e quando devo usar?',
    a_pt: 'O Dataroom é a tua "sala de evidências" para investidores e parceiros: deck, modelo financeiro, métricas, contratos, updates. Permite links partilháveis com prazo e revogação.',
    q_en: 'What is the Dataroom and when should I use it?',
    a_en: 'The Dataroom is your "evidence room" for investors and partners: deck, financial model, metrics, contracts, updates. It allows shareable links with expiry and revocation.',
    tags: ['dataroom', 'fundraising', 'investors'],
    roles: ['founder', 'staff'],
    stages: ['pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-f09',
    q_pt: 'Como funciona a análise IA do modelo financeiro?',
    a_pt: 'Carrega o teu ficheiro Excel/CSV em "Documentos". A plataforma faz parse automático e a IA analisa consistência, unit economics e projeções. Recebes um relatório com sugestões de melhoria.',
    q_en: 'How does the AI financial model analysis work?',
    a_en: 'Upload your Excel/CSV file in "Documents". The platform auto-parses it and AI analyzes consistency, unit economics, and projections. You receive a report with improvement suggestions.',
    tags: ['documents', 'ai', 'fundraising'],
    roles: ['founder', 'staff'],
    stages: ['pre_seed', 'seed', 'scale'],
  },

  // ─── MENTORING & SESSIONS (ALL ROLES) ─────────────────────────────
  {
    id: 'faq-03',
    q_pt: 'Como peço mentoria e o que acontece a seguir?',
    a_pt: 'Em "Mentores", seleciona temas e descreve o que precisas. O pedido fica com estado "Pendente" até ser atribuído. Assim que houver atribuição, recebes notificação e passa a existir um canal de trabalho (sessões, notas e ações).',
    q_en: 'How do I request mentoring and what happens next?',
    a_en: 'In "Mentors", select topics and describe what you need. The request stays "Pending" until assigned. Once assigned, you receive a notification and a work channel is created (sessions, notes, and actions).',
    tags: ['mentoring', 'process'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-04',
    q_pt: 'Como marco uma sessão (e envio convite/Teams)?',
    a_pt: 'Em "Sessões & Mentoria", cria a sessão com data/hora e participantes. Podes gerar link (Teams/online), enviar convite e anexar agenda. Depois da sessão, regista notas e gera resumo/ações com IA.',
    q_en: 'How do I schedule a session (and send a Teams invite)?',
    a_en: 'In "Sessions & Mentoring", create a session with date/time and participants. You can generate a link (Teams/online), send an invite, and attach an agenda. After the session, record notes and generate a summary/actions with AI.',
    tags: ['sessions', 'teams', 'calendar'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-s01',
    q_pt: 'O que são Frameworks de Sessão?',
    a_pt: 'São templates estruturados para diferentes tipos de sessões: Value Prop Canvas, Quality Gates, revisão de pitch, etc. Permitem consistência entre consultores e guardam evidências automaticamente.',
    q_en: 'What are Session Frameworks?',
    a_en: 'They are structured templates for different session types: Value Prop Canvas, Quality Gates, pitch review, etc. They ensure consistency across consultants and automatically save evidence.',
    tags: ['sessions', 'coaching'],
    roles: ['staff', 'mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-s02',
    q_pt: 'Posso gerar um resumo e ações com IA após a sessão?',
    a_pt: 'Sim. Após registar notas na sessão, clica "Gerar Resumo com IA". A IA cria um resumo estruturado e sugere ações concretas. Revê antes de guardar — podes editar tudo.',
    q_en: 'Can I generate a summary and actions with AI after a session?',
    a_en: 'Yes. After recording session notes, click "Generate Summary with AI". AI creates a structured summary and suggests concrete actions. Review before saving — you can edit everything.',
    tags: ['sessions', 'ai'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── FOUNDER: MESSAGING ───────────────────────────────────────────
  {
    id: 'faq-f10',
    q_pt: 'Como funciona o sistema de mensagens?',
    a_pt: 'O chat interno permite comunicação direta com o teu consultor, mentores e equipa. Suporta texto, anexos e é integrado com o contexto da startup. Não substitui email para comunicações formais.',
    q_en: 'How does the messaging system work?',
    a_en: 'The internal chat allows direct communication with your consultant, mentors, and team. It supports text, attachments, and is integrated with the startup context. It does not replace email for formal communications.',
    tags: ['messaging', 'navigation'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── CONSULTANT-SPECIFIC ─────────────────────────────────────────
  {
    id: 'faq-c01',
    q_pt: 'Como funciona o Cockpit / Dashboard do Consultor?',
    a_pt: 'O Cockpit mostra uma visão geral do teu portefólio: startups por risco, sessões da semana, ações pendentes e alertas. Startups "em risco" aparecem em destaque para triagem rápida.',
    q_en: 'How does the Consultant Cockpit / Dashboard work?',
    a_en: 'The Cockpit shows an overview of your portfolio: startups by risk, sessions this week, pending actions, and alerts. "At risk" startups are highlighted for quick triage.',
    tags: ['portfolio', 'navigation'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-c02',
    q_pt: 'O que é o "Startup Health Score"?',
    a_pt: 'É uma pontuação calculada com base em KPIs atualizados, ações concluídas, sessões realizadas e check-ins. Ajuda a priorizar atenção: Verde (saudável), Amarelo (atenção), Vermelho (risco).',
    q_en: 'What is the "Startup Health Score"?',
    a_en: 'It is a score calculated based on updated KPIs, completed actions, sessions held, and check-ins. It helps prioritize attention: Green (healthy), Yellow (attention), Red (at risk).',
    tags: ['portfolio', 'metrics'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-c03',
    q_pt: 'Como funciona o CRM / Pipeline de entrada?',
    a_pt: 'O CRM organiza leads em estágios (Novo Lead → Qualificado → Proposta → Contrato). Podes arrastar entre estágios, registar atividades e ver previsões de conversão.',
    q_en: 'How does the CRM / Intake Pipeline work?',
    a_en: 'The CRM organizes leads in stages (New Lead → Qualified → Proposal → Contract). You can drag between stages, log activities, and view conversion forecasts.',
    tags: ['crm', 'pipeline'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-c04',
    q_pt: 'Como preparo sessões com a startup?',
    a_pt: 'Antes da sessão, revê o dashboard da startup: KPIs recentes, ações pendentes e último check-in. Usa um Framework de Sessão adequado ao tema. Após a sessão, regista notas e define próximos passos.',
    q_en: 'How do I prepare sessions with the startup?',
    a_en: 'Before the session, review the startup dashboard: recent KPIs, pending actions, and last check-in. Use a Session Framework appropriate to the topic. After the session, record notes and define next steps.',
    tags: ['sessions', 'coaching'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-c05',
    q_pt: 'Como uso os relatórios e analytics?',
    a_pt: 'Em "Relatórios" encontras métricas agregadas do portefólio: evolução de KPIs, taxa de conclusão de ações, distribuição por estágio e comparação entre cohorts. Podes exportar em CSV.',
    q_en: 'How do I use reports and analytics?',
    a_en: 'In "Reports" you will find aggregated portfolio metrics: KPI evolution, action completion rate, stage distribution, and cohort comparison. You can export as CSV.',
    tags: ['reports', 'metrics'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-c06',
    q_pt: 'Como atribuo mentores a uma startup?',
    a_pt: 'Na página da startup, em "Equipa & Mentoria", pesquisa mentores disponíveis por área de expertise. O mentor recebe um convite e pode aceitar ou recusar. Podes atribuir múltiplos mentores.',
    q_en: 'How do I assign mentors to a startup?',
    a_en: 'On the startup page, in "Team & Mentoring", search available mentors by area of expertise. The mentor receives an invitation and can accept or decline. You can assign multiple mentors.',
    tags: ['mentoring', 'portfolio'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── MENTOR-SPECIFIC ──────────────────────────────────────────────
  {
    id: 'faq-m01',
    q_pt: 'Como funciona o registo como Mentor?',
    a_pt: 'Cria uma conta, seleciona "Mentor" e espera aprovação. Após aprovação, deves assinar o NDA e preencher o teu perfil com áreas de expertise, disponibilidade e bio.',
    q_en: 'How does Mentor registration work?',
    a_en: 'Create an account, select "Mentor", and wait for approval. After approval, you must sign the NDA and fill in your profile with areas of expertise, availability, and bio.',
    tags: ['onboarding', 'registration'],
    roles: ['mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-m02',
    q_pt: 'O que vejo no meu dashboard de mentor?',
    a_pt: 'O dashboard mostra startups atribuídas, próximas sessões agendadas, pedidos pendentes e notas recentes. Tens acesso ao contexto da startup (saúde, KPIs, milestones) antes de cada sessão.',
    q_en: 'What do I see on my mentor dashboard?',
    a_en: 'The dashboard shows assigned startups, upcoming scheduled sessions, pending requests, and recent notes. You have access to startup context (health, KPIs, milestones) before each session.',
    tags: ['navigation', 'mentoring'],
    roles: ['mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-m03',
    q_pt: 'Quanto contexto vejo sobre a startup?',
    a_pt: 'Vês o health score, KPIs recentes, milestones e ações em curso. Não vês dados financeiros detalhados nem comunicações com outros mentores. Apenas o necessário para mentoria eficaz.',
    q_en: 'How much context do I see about the startup?',
    a_en: 'You see the health score, recent KPIs, milestones, and current actions. You don\'t see detailed financial data or communications with other mentors. Only what\'s needed for effective mentoring.',
    tags: ['permissions', 'mentoring'],
    roles: ['mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-m04',
    q_pt: 'Como registo notas de uma sessão de mentoria?',
    a_pt: 'Abre a sessão no calendário ou em "Notas & Ações". Escreve notas livres ou usa um template. Podes gerar ações concretas diretamente das notas e partilhá-las com a startup.',
    q_en: 'How do I record notes from a mentoring session?',
    a_en: 'Open the session in the calendar or in "Notes & Actions". Write free-form notes or use a template. You can generate concrete actions directly from notes and share them with the startup.',
    tags: ['sessions', 'mentoring'],
    roles: ['mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-m05',
    q_pt: 'Tenho de aceitar cada pedido de mentoria?',
    a_pt: 'Sim. Recebes uma notificação quando és atribuído a uma startup. Podes aceitar ou recusar com justificação. Após aceitar, a startup aparece na tua lista e podes agendar sessões.',
    q_en: 'Do I have to accept each mentoring request?',
    a_en: 'Yes. You receive a notification when assigned to a startup. You can accept or decline with a reason. After accepting, the startup appears in your list and you can schedule sessions.',
    tags: ['mentoring', 'process'],
    roles: ['mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── ADMIN-SPECIFIC ───────────────────────────────────────────────
  {
    id: 'faq-a01',
    q_pt: 'Como aprovo novos utilizadores?',
    a_pt: 'Em "Aprovações" no painel admin, vês contas pendentes. Podes aprovar, rejeitar ou pedir mais informação. A aprovação ativa a conta e o utilizador recebe notificação para iniciar o onboarding.',
    q_en: 'How do I approve new users?',
    a_en: 'In "Approvals" on the admin panel, you see pending accounts. You can approve, reject, or request more information. Approval activates the account and the user receives a notification to start onboarding.',
    tags: ['users', 'onboarding'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-a02',
    q_pt: 'Como crio ou atribuo um workspace a um founder aprovado?',
    a_pt: 'Na gestão de utilizadores, seleciona o founder e usa "Criar e Atribuir Workspace". O sistema sugere automaticamente com base no email/empresa. O workspace é criado com milestones pré-carregados do programa.',
    q_en: 'How do I create or assign a workspace to an approved founder?',
    a_en: 'In user management, select the founder and use "Create and Assign Workspace". The system suggests automatically based on email/company. The workspace is created with pre-loaded milestones from the program.',
    tags: ['users', 'onboarding'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-a03',
    q_pt: 'Como configuro programas e coortes?',
    a_pt: 'Em "Programas & Coortes" no painel admin. Define nome, datas, milestones base, KPIs padrão e consultores. As startups ao entrarem no programa herdam a configuração definida.',
    q_en: 'How do I configure programs and cohorts?',
    a_en: 'In "Programs & Cohorts" on the admin panel. Set name, dates, base milestones, default KPIs, and consultants. Startups joining the program inherit the defined configuration.',
    tags: ['programs', 'settings'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-a04',
    q_pt: 'O que são Feature Flags e como os uso?',
    a_pt: 'Feature Flags permitem ativar/desativar funcionalidades sem deploy. Em "Definições do Sistema", liga ou desliga features como "IA Analysis", "CRM Pipeline", etc., por programa ou globalmente.',
    q_en: 'What are Feature Flags and how do I use them?',
    a_en: 'Feature Flags allow enabling/disabling features without deployment. In "System Settings", toggle features like "AI Analysis", "CRM Pipeline", etc., per program or globally.',
    tags: ['settings', 'admin'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-a05',
    q_pt: 'Como gestiono espaços físicos e edifícios?',
    a_pt: 'Em "Definições do Sistema > Espaços". Define edifícios, gabinetes e áreas disponíveis. Atribui espaços a startups nos contratos. Plantas de piso podem ser carregadas para referência visual.',
    q_en: 'How do I manage physical spaces and buildings?',
    a_en: 'In "System Settings > Spaces". Define buildings, offices, and available areas. Assign spaces to startups in contracts. Floor maps can be uploaded for visual reference.',
    tags: ['settings', 'spaces'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-a06',
    q_pt: 'Como vejo o histórico de ações dos utilizadores?',
    a_pt: 'O Activity Log regista todas as ações significativas: criação de dados, aprovações, alterações de estado. Acede via "Diagnósticos" para auditoria e troubleshooting.',
    q_en: 'How do I see user action history?',
    a_en: 'The Activity Log records all significant actions: data creation, approvals, state changes. Access via "Diagnostics" for auditing and troubleshooting.',
    tags: ['admin', 'security'],
    roles: ['staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── PLAYBOOKS ────────────────────────────────────────────────────
  {
    id: 'faq-06',
    q_pt: 'O que são Playbooks e como funcionam?',
    a_pt: 'Playbooks são percursos práticos (marcos + ações) para acelerar temas comuns (ex.: validação, go-to-market, fundraising). Podes aplicar, completar ações e descartar o que não faz sentido para a tua fase.',
    q_en: 'What are Playbooks and how do they work?',
    a_en: 'Playbooks are practical journeys (milestones + actions) to accelerate common topics (e.g., validation, go-to-market, fundraising). You can apply, complete actions, and dismiss what does not apply to your stage.',
    tags: ['playbooks', 'guides'],
    roles: ['founder', 'staff', 'mentor'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── INTEGRATIONS ─────────────────────────────────────────────────
  {
    id: 'faq-10',
    q_pt: 'Como funcionam as integrações (Teams e Outlook)?',
    a_pt: 'Teams pode ser ligado via webhook/integração para notificações e links de reunião. Outlook pode sincronizar eventos e convites. Se não estiver ligado, continuas a poder exportar ICS e enviar convites manualmente.',
    q_en: 'How do integrations (Teams and Outlook) work?',
    a_en: 'Teams can be connected via webhook/integration for notifications and meeting links. Outlook can sync events and invites. If not connected, you can still export ICS and send invites manually.',
    tags: ['integrations', 'teams', 'outlook'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── AI & SECURITY ────────────────────────────────────────────────
  {
    id: 'faq-11',
    q_pt: 'Como usar a IA com segurança?',
    a_pt: 'A IA ajuda a resumir sessões, sugerir ações e analisar documentos (quando ativado). Não altera nada automaticamente: revês sempre antes de aplicar. Evita colar dados sensíveis desnecessários (segredos comerciais, credenciais, dados pessoais).',
    q_en: 'How do I use AI safely?',
    a_en: 'AI helps summarize sessions, suggest actions, and analyze documents (when enabled). It never changes anything automatically: you always review before applying. Avoid pasting unnecessary sensitive data (trade secrets, credentials, personal data).',
    tags: ['ai', 'security', 'tools'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── TROUBLESHOOTING ──────────────────────────────────────────────
  {
    id: 'faq-12',
    q_pt: 'Porque não estou a ver startups / aparecem "0 resultados"?',
    a_pt: 'Normalmente é filtro (programa/estado), permissões ou falta de associação a um workspace. Confirma os filtros no topo e, se necessário, contacta a equipa para te associar à startup/programa.',
    q_en: 'Why am I not seeing startups / "0 results"?',
    a_en: 'Usually it is a filter (program/status), permissions, or missing workspace association. Check the filters at the top and, if needed, contact the team to associate you with the startup/program.',
    tags: ['troubleshooting', 'permissions', 'filters'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-t01',
    q_pt: 'Os dados da minha startup são carregados lentamente. Porquê?',
    a_pt: 'A plataforma carrega dados em tempo real. Se notas lentidão, pode ser o volume de documentos ou conexão de rede. Tenta recarregar a página. Se persistir, contacta o suporte.',
    q_en: 'My startup data loads slowly. Why?',
    a_en: 'The platform loads data in real time. If you notice slowness, it may be document volume or network connection. Try reloading the page. If it persists, contact support.',
    tags: ['troubleshooting'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-t02',
    q_pt: 'As notificações não estão a chegar. O que faço?',
    a_pt: 'Verifica que o email de contacto no perfil está correto. Verifica a pasta de spam. Notificações in-app aparecem no ícone de sino. Se nada funcionar, contacta o suporte.',
    q_en: 'Notifications are not arriving. What do I do?',
    a_en: 'Check that the contact email in your profile is correct. Check the spam folder. In-app notifications appear on the bell icon. If nothing works, contact support.',
    tags: ['troubleshooting', 'settings'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },

  // ─── SUPPORT & PRODUCTIVITY ───────────────────────────────────────
  {
    id: 'faq-13',
    q_pt: 'Como reporto um problema ou peço ajuda?',
    a_pt: 'Usa "Glossário & FAQ" para respostas rápidas e, se precisares, o botão "Contactar Suporte" para enviar contexto (página, erro e screenshot).',
    q_en: 'How do I report a problem or ask for help?',
    a_en: 'Use "Glossary & FAQ" for quick answers and, if needed, the "Contact Support" button to send context (page, error, and screenshot).',
    tags: ['support', 'help'],
    roles: ['founder', 'mentor', 'staff'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-14',
    q_pt: 'Como tirar mais valor da plataforma em 10 minutos por semana?',
    a_pt: 'Atualiza 2–3 KPIs, fecha 1 ação pendente, agenda (ou prepara) a próxima sessão e mantém 1 documento-chave (deck ou modelo financeiro) sempre atualizado no repositório.',
    q_en: 'How to get the most value from the platform in 10 minutes per week?',
    a_en: 'Update 2–3 KPIs, close 1 pending action, schedule (or prepare) the next session, and keep 1 key document (deck or financial model) always up-to-date in the repository.',
    tags: ['productivity', 'tips', 'onboarding'],
    roles: ['founder'],
    stages: ['ideation', 'pre_seed', 'seed', 'scale'],
  },
  {
    id: 'faq-08',
    q_pt: 'Para onde vai um ficheiro depois de submetido/aprovado?',
    a_pt: 'Tudo o que carregas fica no repositório "Documentos". Se houver um fluxo de submissão/aprovação, o ficheiro passa a ter um badge de estado (ex.: "Aprovado") e pode ser adicionado ao Dataroom com 1 clique.',
    q_en: 'Where does a file go after submission/approval?',
    a_en: 'Everything you upload stays in the "Documents" repository. If there is a submission/approval flow, the file gets a status badge (e.g., "Approved") and can be added to the Dataroom with 1 click.',
    tags: ['documents', 'workflow', 'approval'],
    roles: ['founder', 'staff'],
    stages: ['pre_seed', 'seed', 'scale'],
  },
];
