project_id = "apxzuslwhjujgrcsfzqw"

[functions.send-session-invite]
verify_jwt = false

[functions.send-meeting-invite]
verify_jwt = false

[functions.send-email-digest]
verify_jwt = false

[functions.send-task-notification]
verify_jwt = false

[functions.send-template-notification]
verify_jwt = false
