import { test as base, expect, type Page } from '@playwright/test';
import * as path from 'path';

/**
 * Role-based authentication fixtures for Playwright E2E tests.
 *
 * Uses storageState files generated by global-setup.ts.
 * 
 * Personas:
 *   - founderPage: founder WITH an active workspace (bypasses claim gate)
 *   - founderUnclaimedPage: founder with NO workspace (lands in claim-first gate)
 */

const AUTH_DIR = path.resolve('playwright/.auth');

type AuthFixtures = {
  adminPage: Page;
  backofficePage: Page;
  consultantPage: Page;
  founderPage: Page;
  founderUnclaimedPage: Page;
  mentorPage: Page;
};

function storageStatePath(role: string) {
  return path.join(AUTH_DIR, `${role}.json`);
}

export const test = base.extend<AuthFixtures>({
  adminPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: storageStatePath('admin'),
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  backofficePage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: storageStatePath('backoffice'),
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  consultantPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: storageStatePath('consultant'),
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  founderPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: storageStatePath('founder'),
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  founderUnclaimedPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: storageStatePath('founder_unclaimed'),
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  mentorPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: storageStatePath('mentor'),
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },
});

export { expect };
