#!/bin/bash
# =============================================================================
# Production Smoke Test Script
# =============================================================================
# Run after `npm run build && npm run preview` to verify production readiness.
# Exit codes: 0 = pass, 1 = fail
#
# Usage:
#   chmod +x scripts/smoke-test.sh
#   npm run build && npm run preview &
#   sleep 5  # Wait for preview server
#   ./scripts/smoke-test.sh
# =============================================================================

set -e

BASE_URL="${1:-http://localhost:4173}"
FAILED=0

echo "🔍 Production Smoke Test"
echo "========================"
echo "Testing against: $BASE_URL"
echo ""

# Helper function to check HTTP status
check_url() {
  local url="$1"
  local expected_status="${2:-200}"
  local description="$3"
  
  status=$(curl -s -o /dev/null -w "%{http_code}" "$url" 2>/dev/null || echo "000")
  
  if [ "$status" = "$expected_status" ]; then
    echo "✅ [$status] $description"
    return 0
  else
    echo "❌ [$status] $description (expected $expected_status)"
    FAILED=1
    return 1
  fi
}

# Helper function to check if response contains text
check_contains() {
  local url="$1"
  local search="$2"
  local description="$3"
  
  response=$(curl -s "$url" 2>/dev/null || echo "")
  
  if echo "$response" | grep -q "$search"; then
    echo "✅ $description"
    return 0
  else
    echo "❌ $description (text not found: $search)"
    FAILED=1
    return 1
  fi
}

echo "📋 1. Basic Page Loads"
echo "----------------------"
check_url "$BASE_URL/" 200 "Root path loads"
check_url "$BASE_URL/login" 200 "Login page loads"
check_url "$BASE_URL/my-workspaces" 200 "Protected route redirects (serves index.html)"
check_url "$BASE_URL/some-random-path-12345" 200 "Unknown route serves SPA (not 404)"

echo ""
echo "📋 2. Static Assets"
echo "-------------------"
check_url "$BASE_URL/favicon.ico" 200 "Favicon loads"
check_url "$BASE_URL/pwa-192x192.png" 200 "PWA icon 192x192 loads"
check_url "$BASE_URL/pwa-512x512.png" 200 "PWA icon 512x512 loads"

echo ""
echo "📋 3. SPA Content Verification"
echo "------------------------------"
check_contains "$BASE_URL/" "<div id=\"root\">" "Root element present in HTML"
check_contains "$BASE_URL/" "src=\"/src/main.tsx\"" "Main entry point referenced (dev) OR"
# In production build, it would be a hashed JS file
check_contains "$BASE_URL/" "<script" "Script tag present"

echo ""
echo "📋 4. PWA Manifest"
echo "------------------"
# Note: manifest.webmanifest is generated by vite-plugin-pwa during build
check_url "$BASE_URL/manifest.webmanifest" 200 "PWA manifest accessible"

echo ""
echo "========================"
if [ $FAILED -eq 0 ]; then
  echo "✅ All smoke tests passed!"
  exit 0
else
  echo "❌ Some smoke tests failed!"
  exit 1
fi
